const
  FETCH_ITEMS = "FETCH_ITEMS",
  SET_ITEMS = "SET_ITEMS",
  ADD_ITEM = "ADD_ITEM",
  EDIT_ITEM = "EDIT_ITEM",
  DELETE_ITEM = "DELETE_ITEM";

export default {
  ADD_ITEM,
  SET_ITEMS,
  EDIT_ITEM,
  DELETE_ITEM,
  FETCH_ITEMS
};
